# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildconfiguration: Release

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
    includePreviewVersions: true
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
    performMultiLevelLookup: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Parameters.projects)'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Install dotnetsay'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install -g dotnetsay'
- task: PublishTestResults@2
  inputs: 
    testRunner: VSTest
    testResultsFiles: '**/*.trx'




  
    

